export const cruisesFromAuckland = [
  {
    id: "1",
    name: "Norwegian Spirit",
    nights: "13",
    route: "Auckland → +12 ports",
    reviews: 2131,
    departureDate: "4 Jan, 2026",
    line: "Norwegian Cruise Line",
    images: [
      "https://img.cruisecritic.net/cms-sb/f/1005231/ed57ea9a4b/carnival-cruise-line_carnival-mardi-gras_carnival-horizon_miami_18897608.jpg?auto=format&fit=crop&crop=entropy&q=50&w=2048&ixlib=react-9.8.1",
      "https://www.globalportsholding.com/media/wi3ey33z/las-palmas-960x680.jpg",
      "https://www.marineinsight.com/wp-content/uploads/2025/04/Cruise-ports.jpg",
    ],
  },
  {
    id: "2",
    name: "Crown Princess",
    nights: "25",
    route: "Auckland → +9 ports",
    reviews: 2266,
    departureDate: "9 Nov, 2026",
    line: "Princess Cruises",
    images: [
      "https://www.marineinsight.com/wp-content/uploads/2025/04/Cruise-ports.jpg",
      "https://www.globalportsholding.com/media/wi3ey33z/las-palmas-960x680.jpg",
    ],
  },
  {
    id: "3",
    name: "Celebrity Edge",
    nights: "21",
    route: "Auckland → +5 ports",
    reviews: 205,
    departureDate: "12 Apr, 2026",
    line: "Celebrity Cruises",
    images: [
      "https://www.globalportsholding.com/media/wi3ey33z/las-palmas-960x680.jpg",
      "https://www.marineinsight.com/wp-content/uploads/2025/04/Cruise-ports.jpg",
    ],
  },
  {
    id: "4",
    name: "Noordam",
    nights: "14",
    route: "Auckland → +9 ports",
    reviews: 852,
    departureDate: "1 Mar, 2026",
    line: "Holland America Line",
    images: [
      "https://loveincorporated.blob.core.windows.net/contentimages/gallery/84bc2f7c-529c-49cd-a40f-d5058f2bd6f5-shutterstock_KeyWest_Florida_cruise_port.jpg",
      "https://www.marineinsight.com/wp-content/uploads/2025/04/Cruise-ports.jpg",
    ],
  },
  {
    id: "5",
    name: "Ovation of the Seas",
    nights: "12",
    route: "Auckland → +10 ports",
    reviews: 1340,
    departureDate: "8 Feb, 2026",
    line: "Royal Caribbean",
    images: [
      "https://www.medcruise.com/wp-content/uploads/2021/05/cruise.jpg",
      "https://beyourowntravelguide.com/wp-content/uploads/2024/01/Port-of-Curacao.jpg",
    ],
  },
  {
    id: "5",
    name: "Ovation of the Seas",
    nights: "12",
    route: "Auckland → +10 ports",
    reviews: 1340,
    departureDate: "8 Feb, 2026",
    line: "Royal Caribbean",
    images: [
      "https://www.medcruise.com/wp-content/uploads/2021/05/cruise.jpg",
      "https://beyourowntravelguide.com/wp-content/uploads/2024/01/Port-of-Curacao.jpg",
    ],
  },
  {
    id: "5",
    name: "Ovation of the Seas",
    nights: "12",
    route: "Auckland → +10 ports",
    reviews: 1340,
    departureDate: "8 Feb, 2026",
    line: "Royal Caribbean",
    images: [
      "https://www.medcruise.com/wp-content/uploads/2021/05/cruise.jpg",
      "https://beyourowntravelguide.com/wp-content/uploads/2024/01/Port-of-Curacao.jpg",
    ],
  },
  {
    id: "5",
    name: "Ovation of the Seas",
    nights: "12",
    route: "Auckland → +10 ports",
    reviews: 1340,
    departureDate: "8 Feb, 2026",
    line: "Royal Caribbean",
    images: [
      "https://www.medcruise.com/wp-content/uploads/2021/05/cruise.jpg",
      "https://beyourowntravelguide.com/wp-content/uploads/2024/01/Port-of-Curacao.jpg",
    ],
  },
  {
    id: "5",
    name: "Ovation of the Seas",
    nights: "12",
    route: "Auckland → +10 ports",
    reviews: 1340,
    departureDate: "8 Feb, 2026",
    line: "Royal Caribbean",
    images: [
      "https://www.medcruise.com/wp-content/uploads/2021/05/cruise.jpg",
      "https://beyourowntravelguide.com/wp-content/uploads/2024/01/Port-of-Curacao.jpg",
    ],
  },
  {
    id: "5",
    name: "Ovation of the Seas",
    nights: "12",
    route: "Auckland → +10 ports",
    reviews: 1340,
    departureDate: "8 Feb, 2026",
    line: "Royal Caribbean",
    images: [
      "https://www.medcruise.com/wp-content/uploads/2021/05/cruise.jpg",
      "https://beyourowntravelguide.com/wp-content/uploads/2024/01/Port-of-Curacao.jpg",
    ],
  },
  {
    id: "5",
    name: "Ovation of the Seas",
    nights: "12",
    route: "Auckland → +10 ports",
    reviews: 1340,
    departureDate: "8 Feb, 2026",
    line: "Royal Caribbean",
    images: [
      "https://www.medcruise.com/wp-content/uploads/2021/05/cruise.jpg",
      "https://beyourowntravelguide.com/wp-content/uploads/2024/01/Port-of-Curacao.jpg",
    ],
  },
  {
    id: "5",
    name: "Ovation of the Seas",
    nights: "12",
    route: "Auckland → +10 ports",
    reviews: 1340,
    departureDate: "8 Feb, 2026",
    line: "Royal Caribbean",
    images: [
      "https://www.medcruise.com/wp-content/uploads/2021/05/cruise.jpg",
      "https://beyourowntravelguide.com/wp-content/uploads/2024/01/Port-of-Curacao.jpg",
    ],
  },
  {
    id: "5",
    name: "Ovation of the Seas",
    nights: "12",
    route: "Auckland → +10 ports",
    reviews: 1340,
    departureDate: "8 Feb, 2026",
    line: "Royal Caribbean",
    images: [
      "https://www.medcruise.com/wp-content/uploads/2021/05/cruise.jpg",
      "https://beyourowntravelguide.com/wp-content/uploads/2024/01/Port-of-Curacao.jpg",
    ],
  },
  {
    id: "5",
    name: "Ovation of the Seas",
    nights: "12",
    route: "Auckland → +10 ports",
    reviews: 1340,
    departureDate: "8 Feb, 2026",
    line: "Royal Caribbean",
    images: [
      "https://www.medcruise.com/wp-content/uploads/2021/05/cruise.jpg",
      "https://beyourowntravelguide.com/wp-content/uploads/2024/01/Port-of-Curacao.jpg",
    ],
  },
  {
    id: "5",
    name: "Ovation of the Seas",
    nights: "12",
    route: "Auckland → +10 ports",
    reviews: 1340,
    departureDate: "8 Feb, 2026",
    line: "Royal Caribbean",
    images: [
      "https://www.medcruise.com/wp-content/uploads/2021/05/cruise.jpg",
      "https://beyourowntravelguide.com/wp-content/uploads/2024/01/Port-of-Curacao.jpg",
    ],
  },
  {
    id: "5",
    name: "Ovation of the Seas",
    nights: "12",
    route: "Auckland → +10 ports",
    reviews: 1340,
    departureDate: "8 Feb, 2026",
    line: "Royal Caribbean",
    images: [
      "https://www.medcruise.com/wp-content/uploads/2021/05/cruise.jpg",
      "https://beyourowntravelguide.com/wp-content/uploads/2024/01/Port-of-Curacao.jpg",
    ],
  },
  {
    id: "5",
    name: "Ovation of the Seas",
    nights: "12",
    route: "Auckland → +10 ports",
    reviews: 1340,
    departureDate: "8 Feb, 2026",
    line: "Royal Caribbean",
    images: [
      "https://www.medcruise.com/wp-content/uploads/2021/05/cruise.jpg",
      "https://beyourowntravelguide.com/wp-content/uploads/2024/01/Port-of-Curacao.jpg",
    ],
  },
  {
    id: "5",
    name: "Ovation of the Seas",
    nights: "12",
    route: "Auckland → +10 ports",
    reviews: 1340,
    departureDate: "8 Feb, 2026",
    line: "Royal Caribbean",
    images: [
      "https://www.medcruise.com/wp-content/uploads/2021/05/cruise.jpg",
      "https://beyourowntravelguide.com/wp-content/uploads/2024/01/Port-of-Curacao.jpg",
    ],
  },
  {
    id: "5",
    name: "Ovation of the Seas",
    nights: "12",
    route: "Auckland → +10 ports",
    reviews: 1340,
    departureDate: "8 Feb, 2026",
    line: "Royal Caribbean",
    images: [
      "https://www.medcruise.com/wp-content/uploads/2021/05/cruise.jpg",
      "https://beyourowntravelguide.com/wp-content/uploads/2024/01/Port-of-Curacao.jpg",
    ],
  },
  {
    id: "5",
    name: "Ovation of the Seas",
    nights: "12",
    route: "Auckland → +10 ports",
    reviews: 1340,
    departureDate: "8 Feb, 2026",
    line: "Royal Caribbean",
    images: [
      "https://www.medcruise.com/wp-content/uploads/2021/05/cruise.jpg",
      "https://beyourowntravelguide.com/wp-content/uploads/2024/01/Port-of-Curacao.jpg",
    ],
  },
];
